### ISSUE TITLE
Footer formatting

### ISSUE THREAD

**Issue by thomasdane** [ocius/website#111]
The footer on desktop and mobile does not look right. For example on desktop (Chrome on Windows) I think these items should be to the right? 

<img width="631" alt="desktop" src="https://user-images.githubusercontent.com/2957318/73709430-e8fad900-46b5-11ea-8de2-e949eb5ccf2b.PNG">

Also on mobile (Brave on Android)

![Screenshot_20200203-184506](https://user-images.githubusercontent.com/2957318/73709466-062fa780-46b6-11ea-8fa3-178707c6a908.png)

Tech specs and the other items look strangely layed out?

**Comment by r007** [comment]
Good catch! I think we can safely remove the "Tech Specs" link, because it is duplicated in "Drones" subsection. Maybe Kevin meant "Media Coverage"? Anyway, I replaced "Tech Specs" with "Media Coverage" here.

Here's how footer looks on mobile now:

![Скриншот сделанный 2020-02-06 в 02 43 28](https://user-images.githubusercontent.com/78280/73890612-d2a67600-488b-11ea-9051-57c3b1ae571e.png)
