### ISSUE TITLE
Boat names do not match boat colors

### ISSUE THREAD

**Issue by thomasdane** [ocius/website#52]
**Steps to reproduce**

Go to https://www.ocius.cloud/live/

**Expected**

- The colors of Bruce's name, snailtrail, and boat color are all the same
- The colors of Bob's name, snailtrail, and boat color are all the same

**Actual**

- Bruce's name is yellow, boat is blue, and snail trail is yellow.
- Bob's name is yellow, boat is yellow, and snail trail is blue.

**Comment by r007** [comment]
Done. Code was refactored and all drones are now connected with their locations and have the same color.

**Comment by thomasdane** [comment]
This is great @r007 . Thank you! Could the name colors also match? Right now for me, both drones have a yellow name. Would be good if the name colors could match the boat/snailtrail colors.

**Comment by r007** [comment]
No problem. The color of the label was chosen on purpose. Because yellow is bright and contrasting with the map, so the main goal was to make labels readable. While blue color is hard to read, especially if boat is in the ocean. Blue color of the ocean + blue label = unreadable. Hope this makes sense.

**Comment by thomasdane** [comment]
Great work @r007 . Closing.
