### ISSUE TITLE
Camera images not timely

### ISSUE THREAD

**Issue by peterwlodarczyk** [ocius/website#55]
On the live page, the cameras don't update at the correct rate. Seems like once every few minutes.
usvna page updates every 2 seconds.

**Comment by r007** [comment]
Yes, I've noticed this behaviour. But this is related to API, need to ask @thomasdane what fetching rate he's using. The whole idea of fetching images from usvna and storing them in AWS S3 is very inefficient in the long run. As more and more images will gather up...

**Comment by thomasdane** [comment]
Thanks for the report @peterwlodarczyk ! Yes I had the camera refresh set to every 5 minutes. I have now increased it to every minute. At the moment, that's about as fast as makes sense because the load time of an image is about 30 seconds https://www.webpagetest.org/result/191003_NB_8ae27fa2d057cb611da0cec614fcb2d5/

If that changes, I could fetch new images faster.

**Comment by thomasdane** [comment]
@peterwlodarczyk closing this issue for now. Next time we have a mission, I can set the camera fetching to be as fast as we need it.
