### ISSUE TITLE
Over-caching of home page

### ISSUE THREAD

**Issue by thomasdane** [ocius/website#65]
**Steps to reproduce**

- Publish a new version of the website (merge a PR to master)

**Expected**

- New changes should be visible when loading the page

**Actual**

- Viewing new changes requires a hard refresh or incognito browser

**Possible cause and solution**

<img width="568" alt="homePageCache" src="https://user-images.githubusercontent.com/2957318/66932919-2cd5af80-efed-11e9-8b6e-d17b751cbbbc.PNG">

It looks like the page is being loaded from the service worker, even though the cache-control headers should trigger a revalidation. 

I will look into setting similar headers on the service worker js file as per https://jun711.github.io/web/service-worker-cache-busting/

**Comment by r007** [comment]
Well, yes, if service worker was installed, browser is always trying to retrieve the local version first.

Usually it's not a problem, because the service worker updates automatically when the browser detects that the contents of the ```sw.js``` file have changed from the currently installed version. Upon an update, Gatsby clear all whitelisted paths to prevent old pages from loading after the update.

Here are the links to sw.js file:
https://www.ocius.cloud/sw.js
https://www.ocius.com.au/sw.js

As I checked HTTP-headers, both files has:
**Cache-Control => public, must-revalidate, max-age=0** 

So the question is... what causes such behaviour? I think something happened with service worker on https://ocius.com.au I see an error in console.

![scr12](https://user-images.githubusercontent.com/78280/66979728-9e7e2e00-f0bf-11e9-8dc4-921a39c9d161.png)

While https://ocius.cloud don't have such problem. I think caching is working fine there. Maybe it's worth to just re-install the SW on com.au.

**Comment by r007** [comment]
Done, removed the broken Service Worker. I think users won't notice anything, after some time we can re-install it if needed. Please check, the caching problem should be fixed now.
