### ISSUE TITLE
Improvement: Add loading text to live page

### ISSUE THREAD

**Issue by thomasdane** [ocius/website#91]
Currently when the live page loads, the map shows quickly, but the drones take more time to load. 

This is partly due to the slow load time of AWS API gateway. Largely, this API load time is out of our control. 

To improve perceived performance on the live page, while it is loading the drones can we please add some text at the bottom? 

Some examples of other places this is done:  

**Google Lighthouse**

<img width="394" alt="lightHouseLoading" src="https://user-images.githubusercontent.com/2957318/68969099-0dbb7080-0799-11ea-8ddc-4582bf103419.PNG">

Also the API tool Postman used to do this. 

Can we please add our own? Start with this list: 

Connecting to satellite
Connecting to drones
Drones sending data
Satellite sending to Ocius
Ocius sending to your device

**Comment by r007** [comment]
Done, added the splash screen. Here's the demo:
https://www.youtube.com/watch?v=LtYo2T1AwUY

Right now there is only one API request, so I used this sentence - "Connecting to drones".

**Comment by thomasdane** [comment]
Great work @r007 . Makes sense about the single API request. On mobile, I've seen long load times. How hard is it to have several? If it's a lot of effort, let's just keep one. If it's easy, then please add them all. I don't have a strong preference - one is fine. If we do have one, could it please say "Connecting to satellite'

**Comment by r007** [comment]
@thomasdane thanks. Most likely it's because of the bundle size, **carbon-components** is a vastly bloated library, this is the live page with dropdown (imported from carbon-components-react).

![webpack1](https://user-images.githubusercontent.com/78280/70681456-e3d06d80-1cb4-11ea-9f26-9e88415435e3.png)

And this is the page without:

![dropdown1](https://user-images.githubusercontent.com/78280/70681434-d4512480-1cb4-11ea-8dc1-8ad4d8a325c2.png)

The difference is ~1.5 megabytes. I reported this bug, they are working on it. If they manage to fix the problem, it'll instantly speed up the live page by a couple seconds at least.

Not hard at all, I'll add autorotating text.

**Comment by thomasdane** [comment]
@r007 once loading text is done, let me know and we can close this issue. Sounds exciting about the carbon components bundle - could provide huge speed improvements.

**Comment by r007** [comment]
@thomasdane please check this issue first - https://github.com/ocius/api/issues/7. An autorotating text might not be needed after moving to LambdaNative. I bet we can reduce startup time from 1,000 ms down to 150-200 ms. If this is true, we can forget about rotating text.

**Comment by thomasdane** [comment]
@r007 responded https://github.com/ocius/api/issues/7#issuecomment-574990757

**Comment by r007** [comment]
@thomasdane done. Added rotating text to splash screen (live page). All the changes can be seen on https://www.ocius.cloud/ What do you think of animation?
